# Generated by Django 2.1.1 on 2018-09-14 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20180914_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 16, 5, 58, 53, 849883, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
