# Generated by Django 2.1.1 on 2018-09-15 05:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20180915_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 5, 12, 22, 473344, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
