# Generated by Django 2.1.1 on 2018-09-16 16:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20180916_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 16, 21, 6, 233728, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
