# Generated by Django 2.1.1 on 2018-09-16 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_auto_20180916_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 16, 35, 40, 684319, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
