# Generated by Django 2.1.1 on 2018-09-24 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_auto_20180924_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 18, 52, 19, 724273, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
