# Generated by Django 2.1.1 on 2018-09-25 03:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_auto_20180924_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 3, 56, 34, 554768, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
