# Generated by Django 2.1.1 on 2018-09-15 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_productcategory_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='is_active',
        ),
    ]
